### ISSUE TITLE
Doesn't work on Oreo

### ISSUE THREAD

**Issue by dariusz-goc** [KieronQuinn/DiscoverKiller#1]
Tested with Android 8.1, Nova Launcher and Google app v11.16.13.21.arm64. Still launches Discover feed.

**Comment by KieronQuinn** [comment]
Please post your EdXposed log.

**Comment by Raslin777** [comment]
com.google.android.googlequicksearchbox:interactor(5009-5009): java.util.NoSuchElementException: Array contains no element matching the predicate.
	at com.kieronquinn.app.discoverkiller.Xposed.handleLoadPackage(Xposed.kt:255)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:28)
	at i1.afterHookedMethod(:6)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1188)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2499)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2491)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6511)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1700(ActivityThread.java:232)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1966)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

2021-06-30 03:26:54.054 E/com.google.android.googlequicksearchbox:search(5573-5573): java.util.NoSuchElementException: Array contains no element matching the predicate.
	at com.kieronquinn.app.discoverkiller.Xposed.handleLoadPackage(Xposed.kt:255)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:28)
	at i1.afterHookedMethod(:6)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1188)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2499)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2491)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6511)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1700(ActivityThread.java:232)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1966)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by KieronQuinn** [comment]
The minSDK with version 2.0 is now 29 due to some compatibility requirements. If there's demand I could _maybe_ port it down.

The unrelated crash in this issue is no longer a problem though.

**Comment by dariusz-goc** [comment]
> The minSDK with version 2.0 is now 29 due to some compatibility requirements. If there's demand I could _maybe_ port it down.
> 
> The unrelated crash in this issue is no longer a problem though.

Could you port it down to Oreo?
